version: "3"
services: 
  mariadb1:
    build: 
      context: .  
      dockerfile: Dockerfile  
    image: galeramariadb:11.1.x
    container_name: mariadb1
    ports:
      - "3311:3306"
    env_file: .master.env
    environment:
      - MARIADB_USER=${MARIADB_USER_1}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD_1}
      - MARIADB_DATABASE=${MARIADB_DATABASE_1}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./galera-master-mariadb1.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
    cap_add:
      - all
    networks:
      - mariadb

  mariadb2:
   build: 
      context: .  
      dockerfile: Dockerfile  
   image: galeramariadb:11.1.x
   container_name: mariadb2
   ports:
    - "3312:3306"
   env_file: .node.env   
   environment:
    - MARIADB_USER=${MARIADB_NODE_USER}
    - MARIADB_PASSWORD=${MARIADB_NODE_PASSWORD}
    - MARIADB_DATABASE=${MARIADB_NODE_DATABASE}
    - MARIADB_ROOT_PASSWORD=${MARIADB_NODE_ROOT_PASSWORD}
   volumes:
    - ./mariadb2/galera.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
   cap_add:
    - all
   networks:
    - mariadb

  #mariadb-2
  mariadb3:
   build: 
      context: .  
      dockerfile: Dockerfile  
   image: galeramariadb:11.1.x
   container_name: mariadb3
   ports:
    - "3313:3306"
   env_file: .node.env
   volumes:
    - ./mariadb3/galera.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
   environment:
    - MARIADB_USER=${MARIADB_NODE_USER}
    - MARIADB_PASSWORD=${MARIADB_NODE_PASSWORD}
    - MARIADB_DATABASE=${MARIADB_NODE_DATABASE}
    - MARIADB_ROOT_PASSWORD=${MARIADB_NODE_ROOT_PASSWORD}
   cap_add:
    - all
   networks:
    - mariadb
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "3307:3307"
    networks:
      - galera

networks:
  mariadb:
     driver: bridge
